/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../agility-cms-management-sdk-typescript/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
      },
    },
  },
  plugins: [],
  safelist: [
    // Ensure commonly used classes are always included
    'backdrop-blur-sm',
    'backdrop-blur-md',
    'bg-gradient-to-r',
    'from-blue-500',
    'to-purple-600',
    'hover:from-blue-600', 
    'hover:to-purple-700',
    'transform',
    'hover:scale-105',
    'transition-all',
    'duration-200',
    'animate-pulse',
    'border-t-2',
    'border-blue-200',
    'shadow-2xl',
    'ring-2',
    'ring-blue-200',
    'focus:ring-blue-500',
    'focus:border-blue-500',
    // Dark mode classes
    'dark:bg-gray-800',
    'dark:text-gray-100',
    'dark:border-gray-600',
    'dark:bg-gray-700',
    
    // SDK Dynamic Classes - Prevent purging
    'bg-green-500',
    'bg-yellow-500', 
    'bg-red-500',
    'bg-blue-500',
    'bg-purple-500',
    'bg-gray-500',
    'bg-white',
    'bg-black',
    'text-white',
    'text-black',
    'text-gray-900',
    'text-gray-100',
    'text-gray-400',
    'text-gray-500',
    'hover:bg-gray-800',
    'hover:bg-gray-500',
    'hover:bg-purple-500',
    'border-gray-700',
    'border-gray-200',
    'border-gray-600',
    'border-purple-600',
    'rounded-2xl',
    'rounded-lg',
    'shadow-xl',
    'p-2',
    'p-4',
    'p-8',
    'px-3',
    'px-4',
    'px-8',
    'py-2',
    'py-3',
    'px-6',
    'mt-4',
    'mt-6',
    'mt-8',
    'mx-auto',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'min-w-[140px]',
    'min-w-[120px]',
    'max-w-[25vw]',
    'w-full',
    'h-auto',
    'gap-2',
    'gap-3',
    'gap-4',
    'fixed',
    'sticky',
    'top-0',
    'left-0',
    'right-0',
    'z-10',
    'z-50',
    'transition-all',
    'duration-300',
    'text-xs',
    'text-sm',
    'text-base',
    'text-2xl',
    'font-bold',
    'font-medium',
    'overflow-hidden',
    
    // Custom Select Component Classes
    'rotate-180',
    'transition-transform',
    'transition-colors',
    'duration-150',
    'duration-200',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:border-gray-400',
    'hover:scale-105',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:border-blue-500',
    'focus:bg-gray-100',
    'bg-blue-50',
    'text-blue-600',
    'text-gray-700',
    'text-gray-600',
    'text-gray-400',
    'border-gray-300',
    'shadow-sm',
    'shadow-lg',
    'max-h-60',
    'overflow-auto',
    'truncate',
    'flex-shrink-0',
    'absolute',
    'relative',
    'inset-y-0',
    'pointer-events-none',
    'z-50',
    'ml-2',
    'pr-3',
    'w-4',
    'h-4',
    'w-10',
    'h-10',
    'inline-flex',
    'cursor-not-allowed',
    'opacity-50',
    
    // Search functionality classes
    'bg-yellow-200',
    'text-yellow-900',
    'border-b',
    'border-gray-200',
    'focus:ring-1',
    'font-mono',
    'min-w-0',
    'flex-1',
    'max-h-80',
    'max-h-60',
    'w-64',
    'ml-auto',
    'text-center',
  ],
}; 